export const LOGIN = 'LOGIN';
export const LOGOUT  = 'LOGOUT';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS';
export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
